# Generated by Django 5.0.2 on 2024-03-08 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='thumbnail',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='thumbnails', to='blog.image'),
            preserve_default=False,
        ),
    ]
